project:
  type: website
  
website:
  title: "Robert C. Cline, Sr."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - deutsch.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

bibliography: references.bib
editor: visual


preview:
  browser: false
  port: 4200