---
title: "Leben in der DDR"
categories: [Artikel]
date: "2023-12-26"
---

::: {.callout-tip}
## *Planet Wissen* - Eine Ressource für Studierende.

Suchen Sie interessante Ressourcen für Artikel auf Deutsch? Der folgende Artikel stammt von einer Website namens *Planet Wissen*\*. Diese Website wurde erstellt, um Schülern und Studenten eine interessante Ressource zum Lernen über Deutschland und die deutsche Sprache zu bieten. Schauen Sie sich die Hyperlinks zur Website von Planet Wissen an.
:::

Wichtige worter:

**Erwerbstätig** Employed **Weihen** consecrations, blessings or dedications.\
**geloben** pledge\
**Die Gelobten** **Die Gelöbnis** pledge or oath, vow.\
**Ein Vortrag vs. eine Ansprache** **Pensum an Arbeit**\
**bewältigen** cope with or manage **Überreichung** presentation or hand over **Anschließen** connect, attach, or join

## [Alltag in der DDR](https://www.planet-wissen.de/geschichte/deutsche_geschichte/ddr/ddr-der-alltag-100.html)

Die Partei SED (Sozialistische Einheitspartei Deutschlands) wachte über die Menschen in der DDR. Bei Erziehung, Berufswahl und Wohnungssuche hatte sie die Finger im Spiel. Bereits im Kindergarten wurden die Kleinen in der Ideologie des Sozialismus erzogen.

*Von Wiebke Ziegler und Andrea Oster*

-   Kinder und Beruf waren gut vereinbar\
-   "Für Frieden und Sozialismus seid bereit"\
-   Die Jugendweihe\
-   Arbeiten im Kollektiv\
-   60 Quadratmeter für eine vierköpfige Familie\
-   Freizeit, Kultur und Sport

### Kinder und Beruf waren gut vereinbar

Das Leben in der DDR war von der Geburt bis zum Berufsleben durchgeplant. Frauen waren ebenso wie Männer berufstätig. Nur wenige *Betriebe* [^1] boten *Halbtagsstellen* an. Die Kleinkinder kamen schon mit dem ersten Lebensjahr in die Kinderkrippe. Jedem Kind stand ein Platz in der Ganztagsbetreuung zu.

[^1]: *Betriebe* = companies

Mit drei Jahren wechselten die Kinder von der Krippe in den Kindergarten. Bis zu ihrem sechsten Lebensjahr bereiteten die Erzieherinnen sie hier auf die Schule vor. Außerdem sollten die Kinder von Anfang an zu guten Sozialisten und Patrioten erzogen werden. Schon die ganz Kleinen sollten sich mit der SED identifizieren.

Das Bildungssystem war darauf ausgelegt, allen Kindern die gleiche Ausbildung zu ermöglichen. Für die Erziehungsarbeit in den Kindergärten und in den Schulen gab es feste Lehrpläne, an die die Erzieherinnen sich halten mussten.

Alter von sechs Jahren kamen die Kinder in die allgemeinbildende Polytechnische Oberschule (POS), an der sie bis zur zehnten Klasse blieben. Von zehn Schülern machten acht bis neun eine Berufsausbildung. Nur wenige studierten.

Die Plätze an den Universitäten wurden nach bestimmten Kriterien vergeben: Wer sehr gute Noten schrieb, hatte Chancen auf ein Studium. Es half, sich in der Politik oder in der Gesellschaft zu engagieren. Auch die Situation auf dem Arbeitsmarkt konnte den Zugang zum Studium beeinflussen. Jugendliche, deren Eltern Christen oder Oppositionelle waren, hatten geringere Aussichten auf einen Studienplatz.

### "Für Frieden und Sozialismus seid bereit"

Mit Eintritt ins Schulleben wurde jeder Schüler automatisch in die "*Pionierorganisation* Ernst Thälmann" aufgenommen, einer Unterorganisation der Freien Deutschen Jugend (FDJ). Das Ziel der Organisation war es, die Kinder zur Parteitreue zu erziehen. In der Schule begann fast jede Unterrichtsstunde mit den Parolen :[^2] der Pioniere. Die ersten Jahre bei den Pionieren dienten dazu, die Kleinen im Alter von sechs bis 13 Jahren auf Mitgliedschaft in der FDJ vorzubereiten.

[^2]: *parolen* = slogans

Das Jugendgesetz schrieb die Mitgliedschaft bis zum 25 Lebensjahr vor. Die Entscheidung, Pionier zu werden, wurde offiziell gerne als persönliche Entscheidung dargestellt. Eine Karriere war ohne Mitgliedschaft kaum möglich.

*Die Jungpioniere* übernahmen unter anderem gemeinnützige Aufgaben, sie reinigten öffentliche Plätze und pflegten alte Menschen. Die FDJ betrieb zudem Diskotheken, organisierte Freizeit- und Sportveranstaltungen und sendete ein eigenes Jugendprogramm im Fernsehen und im Radio.

### Die Jugendweihe [^3]

[^3]: *Die Jugendweihe* = The **Youth Consecration**

Das Politbüro der SED beschloss [^4] 1954 die Einführung der **Jugendweihe**. Sie sollte Ersatzritual für kirchliche Feiern wie Kommunion und Konfirmation sein. Den Kirchen sollte damit auch gleichzeitig die Möglichkeit genommen werden, Jugendliche durch diese feierliche Zeremonie für sich zu gewinnen.

[^4]: *beschloss* = decided

1955 fanden die ersten **Weihen** [^5] statt. Die Jugendlichen ab der achten Klasse wurden damit in den *Kreis der Erwachsenen* aufgenommen. Oder politisch ausgedrückt [^6] *der großen Gemeinschaft des werktätigen Volkes*.

[^5]: *Weihen* = consecrations

[^6]: *politisch ausgedrückt* = in political terms: Sie waren nun Teil

Schon Wochen vor dem eigentlich Termin *bereiteten* sich die Teilnehmer darauf *vor*. In der Regel gab es einen *speziellen Unterricht*, in dem die Geschichte der Arbeiterbewegung und die Entwicklung des sozialistischen Gesellschaftssystems erläutert wurde.

Zur Feier selbst gehörte ein Festprogramm mit Musik, einer **Ansprache**, der **Überreichung** einer **Urkunde sowie dem Gelöbnis** [^7]. Die Jugendlichen **gelobten** [^8], sich für die Sache des Sozialismus einzusetzen, den Bruderbund mit der Sowjetunion zu vertiefen, im Geiste des proletarischen Internationalismus zu kämpfen, den Frieden zu schützen und den Sozialismus gegen jeden imperialistischen Angriff zu verteidigen.

[^7]: *einer Ansprache, der Überreichung einer Urkunde sowie dem Gelöbnis* = in a speech, the presentation of a certificate, and the pledge

[^8]: *gelobten* = pledged

### Arbeiten im Kollektiv

Die DDR verstand sich selbst als ein Staat der Arbeiter und Bauern. So stand es in der Verfassung der DDR. Für jeden Bürger galt per Gesetz *das Recht auf Arbeit*. Jeder Schulabgänger konnte sicher sein, einen Ausbildungsplatz und **anschließend** [^9] einen Arbeitsplatz zu finden.

[^9]: *anschließend* = subsequently

Gleichzeitig bestand jedoch auch die <u>*Pflicht zur Arbeit*</u>. Wer nicht arbeitete, musste mit einer Geldstrafe rechnen, im schlimmsten Fall mit einer **Gefängnisstrafe**.

Die Arbeit kam in der DDR vor allem anderen. Es ging hierbei nicht nur um die Erfüllung des Volkswirtschaftsplans. Die Arbeiter waren in **Brigaden** organisiert. Für viele waren die Mitglieder der eigenen Brigade der engste Freundeskreis.

Ein Mensch könne seine Fähigkeiten am besten in der Gruppe entfalten [^10] – das war ein **Grundprinzip des Sozialismus**. Im Kollektiv zu arbeiten, unterstrich den Gedanken der **Solidarität** und des Zusammenhalts. Konkurrenz gab es nicht, zumindest in der Theorie.[^11]

[^10]: :*entfalten* = unfold

[^11]: Working collectively emphasized the idea of solidarity and unity. Competition did not exist, at least in theory

In diesem System war es vor allem wichtig, das **Pensum an Arbeit** [^12] in einer bestimmten Zeit zu bewältigen. Alle Arbeitskräfte, die verfügbar waren, wurden eingesetzt. Nach einer Statistik der Konrad Adenauer Stiftung war 1989 etwa die Hälfte der Gesamtbevölkerung in der DDR berufstätig, 8,47 Millionen Menschen. Von den Frauen waren 91,2 Prozent erwerbstätig, in der BRD nur etwa 50 Prozent. Der DDR-Bürger arbeitete im Schnitt 43,5 Stunden pro Woche, Schichtarbeiter 40 Stunden. [^13]

[^12]: *Pensum an Arbeit* = workload

[^13]: Alle Arbeitskräfte, die verfügbar waren, wurden eingesetzt. Nach einer Statistik der Konrad Adenauer Stiftung war 1989 etwa die Hälfte der Gesamtbevölkerung in der DDR berufstätig, 8,47 Millionen Menschen. Von den Frauen waren 91,2 Prozent erwerbstätig, in der BRD nur etwa 50 Prozent. Der DDR-Bürger arbeitete im Schnitt 43,5 Stunden pro Woche, Schichtarbeiter 40 Stunden.

Dass so viele Frauen in der DDR ganztags im Beruf waren, lag an der familienverträglichen Politik. Mütter bekamen nach der Geburt bis zu ein Jahr lang Geld vom Staat. Ab dem ersten Lebensjahr stand jedem Kind ein **Betreuungsplatz** \[*Betreuungsplatz* = child care spot\] zu. War das Kind krank, wurde eine Mutter umgehend von der Arbeit freigestellt [^14] Alleinstehende standen unter besonderem Kündigungsschutz.

[^14]: *umgehend von der Arbeit freigestellt* = immediately granted leave from work

### 60 Quadratmeter für eine vierköpfige Familie

Nach dem Krieg gab es nur wenige Wohnungen, viele Häuser waren ganz zerstört oder nur teilweise bewohnbar. Ein Großteil der Mietshäuser war zu Beginn der 1950er-Jahre verstaatlicht worden und für Neubauten sorgte allein der Staat, er regelte den Wohnungsmarkt. Wer wann wohin umziehen durfte, entschied das zuständige Amt für **Wohnungswesen**.

Die Wohnungen wurden nach verschiedenen Kriterien zugeteilt. So war unter anderem entscheidend, wie dringend der Umzug war und wie viel Platz der Antragssteller bisher zur Verfügung hatte. Einem Vierpersonenhaushalt standen etwa 60 Quadratmeter zu. Viele warteten oft mehrere Monate auf eine neue Immobilie.

Viele Wohnhäuser waren in einem desolaten Zustand, vor allem die Altbauten. Nur wenige Wohnungen verfügten \^*verfügten* = disposed or had\] über ein Bad oder Warmwasser. Es mangelte an Arbeitskräften, um die Häuser umfassend [^15] zu sanieren.

[^15]: *umfassend* = comprehensive or all-encompassing

Die Mieten waren staatlich festgelegt: Nach Angaben der Konrad Adenauer Stiftung lagen sie zwischen 30 bis 50 Pfennig pro Quadratmeter für Altbauten und einer Mark pro Quadratmeter für **Plattenbauten** \^I\[*Plattenbauten* = prefabricated\]. Den Hausbesitzern war es verboten, sich durch die Mieteinnahmen zu bereichern.[^16] Vielen fehlte das Geld für eine Renovierung.

[^16]: Homeowners were forbidden from enriching themselves through rental income.

### Freizeit, Kultur und Sport

Kino, Theater und Museen – das Freizeitangebot in der DDR war vielfältig. Systemkritische Inhalte waren jedoch **untersagt** [^17], sie wurden vor ihrer Veröffentlichung zensiert. Freizeitaktivitäten dienten der sozialistischen Bildung. Was nicht den Grundsätzen der SED-Regierung entsprach, wurde abgesägt [^18].

[^17]: *untersagt* = prohibited

[^18]: *abgesägt* = curtailed

An Literatur jenseits von Abenteuerromanen und Reiseberichten war kaum heranzukommen [^19]. Wer Westliteratur oder anti-sozialistische Literatur lesen wollte, konnte dies – wenn überhaupt – nur unter Aufsicht tun.

[^19]: *kaum heranzukommen* = scarecely possible

Der *Sport hatte in der DDR einen hohen Stellenwert*. Kinder und Jugendliche traten in Wettkämpfen regelmäßig gegeneinander an. Wer Talent besaß [^20], wurde an einer Sportschule gefördert und zum Leistungssportler trainiert. Die SED beeinflusste auch den Sport. Erfolge wie die Olympia-Medaillengewinne von 1980 in Moskau bedeuteten für die DDR immer auch einen Sieg des Sozialismus über den Kapitalismus.

[^20]: *besaß* = possessed

------------------------------------------------------------------------
